site_name: Usaconドキュメント
site_url: https://docs.usacloud.jp/usacon
site_description: Usacon日本語ドキュメント
site_author: '@sacloud-authors'
copyright: Copyright (C) 2017-2022 The Usacon Authors.
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
extra:
  analytics:
    provider: google
    property: G-9JFNZ70H7B
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Usaconドキュメント: index.md
