name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - './src/terraform'
          - './src/terraform-policy'
          - './src/top'
          - './src/usacloud'
          - './src/autoscaler'
          - './src/prometheus'
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: lint a document with textlint
        uses: sacloud/textlint-action@c08eeef08206a78cb548e70c74025827b67a449f # v0.0.1
        with:
          working-directory: ${{ matrix.working-directory }}
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Build a document with mkdocs - src/terraform
        uses: ./.github/actions/mkdocs
        with:
          working-directory: './src/terraform'

      - name: Build a document with mkdocs - src/terraform-policy
        uses: ./.github/actions/mkdocs
        with:
          working-directory: './src/terraform-policy'

      - name: Build a document with mkdocs - src/top
        uses: ./.github/actions/mkdocs
        with:
          working-directory: './src/top'

      - name: Build a document with mkdocs - src/usacloud
        uses: ./.github/actions/mkdocs
        with:
          working-directory: './src/usacloud'

      - name: Build a document with mkdocs - src/autoscaler
        uses: ./.github/actions/mkdocs
        with:
          working-directory: './src/autoscaler'

      - name: Build a document with mkdocs - src/prometheus
        uses: ./.github/actions/mkdocs
        with:
          working-directory: './src/prometheus'
